export const languagesMap = {
  placeholder: 'Original Language',
  en: 'English',
  de: 'Deutsch',
  uk: 'Ukrainian',
  es: 'Spanish',
  fr: 'French',
  it: 'Italian',
  pt: 'Portuguese',
  ru: 'Russian',
  zh: 'Chinese',
  ja: 'Japanese',
  ko: 'Korean',
  ar: 'Arabic',
  hi: 'Hindi',
  bn: 'Bengali',
  pa: 'Punjabi',
  jv: 'Javanese',
  tr: 'Turkish',
  vi: 'Vietnamese',
  pl: 'Polish',
  nl: 'Dutch',
  sv: 'Swedish',
  no: 'Norwegian',
  fi: 'Finnish',
  da: 'Danish',
  cs: 'Czech',
  hu: 'Hungarian',
  el: 'Greek',
  ro: 'Romanian',
  bg: 'Bulgarian',
  hr: 'Croatian',
  sr: 'Serbian',
  sk: 'Slovak',
  sl: 'Slovenian',
} as const;
