on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
        - uses: actions/checkout@v5
        - run: cd frontend
        - run: npm install
        - run: npm run build
        - run: npx prettier src/ -c

